# Generated by Django 4.2.7 on 2026-07-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_photo'),
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngay lam viec')),
                ('expected_work_days', models.FloatField(default=1, verbose_name='So cong du kien')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_schedules', to='employees.employee', verbose_name='Nhan vien')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to='attendance.workshift', verbose_name='Ca lam viec')),
            ],
            options={
                'verbose_name': 'Lich lam viec',
                'verbose_name_plural': 'Lich lam viec',
                'ordering': ['-date', 'employee__code'],
                'unique_together': {('employee', 'date', 'work_shift')},
            },
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='attendance.employeeschedule', verbose_name='Lịch làm việc'),
        ),
    ]
