# Generated by Django 4.2.7 on 2026-08-01 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_basic_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_employeeschedule_dailyattendance_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngay hoc')),
                ('start_time', models.TimeField(verbose_name='Gio bat dau')),
                ('end_time', models.TimeField(verbose_name='Gio ket thuc')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phong hoc')),
                ('status', models.CharField(choices=[('scheduled', 'Da xep lich'), ('completed', 'Da day'), ('cancelled', 'Da huy'), ('makeup', 'Day bu')], default='scheduled', max_length=20, verbose_name='Trang thai')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buoi hoc',
                'verbose_name_plural': 'Buoi hoc',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Ma lop/khoa hoc')),
                ('name', models.CharField(max_length=200, verbose_name='Ten lop/khoa hoc')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cap do')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngay bat dau')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngay ket thuc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang hoat dong')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lop/Khoa hoc',
                'verbose_name_plural': 'Lop/Khoa hoc',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Thang')),
                ('year', models.IntegerField(verbose_name='Nam')),
                ('name', models.CharField(max_length=200, verbose_name='Ten bang cong thang')),
                ('status', models.CharField(choices=[('draft', 'Nhap'), ('approved', 'Da duyet'), ('locked', 'Da khoa'), ('transferred', 'Da chuyen luong')], default='draft', max_length=20, verbose_name='Trang thai')),
                ('transferred', models.BooleanField(default=False, verbose_name='Da chuyen tinh luong')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_timesheets', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vi tri')),
            ],
            options={
                'verbose_name': 'Bang cong thang',
                'verbose_name_plural': 'Bang cong thang',
                'ordering': ['-year', '-month', 'position__code'],
                'unique_together': {('month', 'year', 'position')},
            },
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-start_date'], 'verbose_name': 'Bang cham cong chi tiet cu', 'verbose_name_plural': 'Bang cham cong chi tiet cu'},
        ),
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bang cham cong tong hop cu', 'verbose_name_plural': 'Bang cham cong tong hop cu'},
        ),
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'verbose_name': 'Cham cong nhan vien van hanh', 'verbose_name_plural': 'Cham cong nhan vien van hanh'},
        ),
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'verbose_name': 'Cham cong nhan vien cu', 'verbose_name_plural': 'Cham cong nhan vien cu'},
        ),
        migrations.AlterModelOptions(
            name='employeeschedule',
            options={'ordering': ['-date', 'employee__code'], 'verbose_name': 'Lich lam viec cu', 'verbose_name_plural': 'Lich lam viec cu'},
        ),
        migrations.AlterModelOptions(
            name='workshift',
            options={'verbose_name': 'Ca lam viec', 'verbose_name_plural': 'Ca lam viec'},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='apply_to_all_shifts',
            field=models.BooleanField(default=False, verbose_name='Chon tat ca ca'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(choices=[('shift', 'Theo ca'), ('daily', 'Theo ngay')], max_length=20, verbose_name='Hinh thuc cham cong'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='end_date',
            field=models.DateField(verbose_name='Ngay ket thuc'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ten bang cham cong'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vi tri ap dung'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='start_date',
            field=models.DateField(verbose_name='Ngay bat dau'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='work_shifts',
            field=models.ManyToManyField(blank=True, to='attendance.workshift', verbose_name='Ca lam viec'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='attendance_records',
            field=models.ManyToManyField(to='attendance.attendancerecord', verbose_name='Danh sach bang cham cong chi tiet'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngay ket thuc'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='month',
            field=models.IntegerField(default=1, verbose_name='Thang'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ten bang cham cong tong hop'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vi tri ap dung'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='standard_workdays',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5, verbose_name='So cong chuan'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngay bat dau'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='transferred',
            field=models.BooleanField(default=False, verbose_name='Da chuyen tinh luong'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Nam'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='actual_work_days',
            field=models.FloatField(default=1, verbose_name='So cong di lam thuc te'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='attendance.attendancerecord', verbose_name='Bang cham cong cu'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_status',
            field=models.CharField(choices=[('not_absent', 'Khong nghi'), ('permitted_absence', 'Nghi co phep'), ('unpermitted_absence', 'Nghi khong phep'), ('regime_absence', 'Nghi theo che do')], default='not_absent', max_length=20, verbose_name='Trang thai nghi'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Gio vao'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Gio ra'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(verbose_name='Ngay cham cong'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhan vien'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='paid_work_days',
            field=models.FloatField(default=1, verbose_name='So cong huong luong'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='attendance.employeeschedule', verbose_name='Lich lam viec cu'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift', verbose_name='Ca lam viec'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendance_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='attendance.attendancesummary', verbose_name='Bang cham cong tong hop cu'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhan vien'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='late_early_minutes',
            field=models.IntegerField(default=0, verbose_name='Di muon/ve som (phut)'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='paid_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghi co luong'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='policy_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghi che do'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='unpaid_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghi khong luong'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='workdays',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='So cong lam viec'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='apply_to_all',
            field=models.BooleanField(default=False, verbose_name='Toan don vi'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='check_in_end',
            field=models.TimeField(verbose_name='Cham vao - Den'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='check_in_start',
            field=models.TimeField(verbose_name='Cham vao - Tu'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='check_out_end',
            field=models.TimeField(verbose_name='Cham ra - Den'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='check_out_start',
            field=models.TimeField(verbose_name='Cham ra - Tu'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Ma ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='deduct_if_no_check_in',
            field=models.BooleanField(default=False, verbose_name='Tru cong neu khong co gio vao'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='deduct_if_no_check_out',
            field=models.BooleanField(default=False, verbose_name='Tru cong neu khong co gio ra'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employees.employee', verbose_name='Danh sach nhan vien'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.TimeField(verbose_name='Gio ket thuc ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='has_break',
            field=models.BooleanField(default=False, verbose_name='Co nghi giua ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='holiday_coefficient',
            field=models.FloatField(default=3, verbose_name='He so ngay le'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ten ca lam viec'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='normal_day_coefficient',
            field=models.FloatField(default=1, verbose_name='He so ngay thuong'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='rest_day_coefficient',
            field=models.FloatField(default=2, verbose_name='He so ngay nghi'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.TimeField(verbose_name='Gio bat dau ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='work_days',
            field=models.FloatField(default=1, verbose_name='Ngay cong'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='work_hours',
            field=models.FloatField(default=0, verbose_name='Gio cong'),
        ),
        migrations.CreateModel(
            name='TimesheetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reviewed', 'Da ra soat'), ('approved', 'Da duyet'), ('locked', 'Da khoa'), ('reopened', 'Mo khoa')], max_length=20, verbose_name='Hanh dong')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monthly_timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='attendance.monthlytimesheet', verbose_name='Bang cong thang')),
            ],
            options={
                'verbose_name': 'Lich su duyet bang cong',
                'verbose_name_plural': 'Lich su duyet bang cong',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Giao vien'), ('assistant', 'Tro giang'), ('substitute', 'Day thay')], default='teacher', max_length=20, verbose_name='Vai tro')),
                ('expected_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Gio du kien')),
                ('pay_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='He so tinh luong')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.classsession', verbose_name='Buoi hoc')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='employees.employee', verbose_name='Nhan su')),
            ],
            options={
                'verbose_name': 'Phan cong giang day',
                'verbose_name_plural': 'Phan cong giang day',
                'unique_together': {('class_session', 'employee', 'role')},
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngay lam viec')),
                ('expected_work_days', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Cong du kien')),
                ('status', models.CharField(choices=[('planned', 'Da xep lich'), ('cancelled', 'Da huy')], default='planned', max_length=20, verbose_name='Trang thai')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='employees.employee', verbose_name='Nhan vien')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='attendance.workshift', verbose_name='Ca lam viec')),
            ],
            options={
                'verbose_name': 'Lich ca nhan vien van hanh',
                'verbose_name_plural': 'Lich ca nhan vien van hanh',
                'ordering': ['-date', 'employee__code'],
                'unique_together': {('employee', 'date', 'work_shift')},
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('taught', 'Da day'), ('absent_excused', 'Nghi co phep'), ('absent_unexcused', 'Nghi khong phep'), ('substituted', 'Co nguoi day thay'), ('cancelled_by_center', 'Lop huy boi trung tam'), ('cancelled_by_teacher', 'Giao vien huy'), ('online', 'Day online'), ('makeup', 'Day bu')], default='taught', max_length=30, verbose_name='Trang thai')),
                ('actual_start_time', models.TimeField(blank=True, null=True, verbose_name='Gio bat dau thuc te')),
                ('actual_end_time', models.TimeField(blank=True, null=True, verbose_name='Gio ket thuc thuc te')),
                ('paid_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Gio tinh luong')),
                ('approved', models.BooleanField(default=False, verbose_name='Da duyet')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.teacherassignment', verbose_name='Phan cong')),
            ],
            options={
                'verbose_name': 'Cham cong buoi day',
                'verbose_name_plural': 'Cham cong buoi day',
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.course', verbose_name='Lop/Khoa hoc'),
        ),
        migrations.CreateModel(
            name='AttendanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('workday', 'Dieu chinh ngay cong'), ('hour', 'Dieu chinh gio day/lam'), ('paid_leave', 'Dieu chinh nghi co luong'), ('unpaid_leave', 'Dieu chinh nghi khong luong'), ('note', 'Ghi chu')], max_length=20, verbose_name='Loai dieu chinh')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gia tri')),
                ('reason', models.TextField(verbose_name='Ly do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhan vien')),
                ('monthly_timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='attendance.monthlytimesheet', verbose_name='Bang cong thang')),
            ],
            options={
                'verbose_name': 'Dieu chinh cong',
                'verbose_name_plural': 'Dieu chinh cong',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='staff_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='attendance.staffschedule', verbose_name='Lich ca nhan vien'),
        ),
    ]
