# Generated by Django 4.2.7 on 2026-08-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_classsession_course_monthlytimesheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='So phut nghi giua ca'),
        ),
    ]
