# Generated by Django 4.2.7 on 2026-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_basic_salary_and_more'),
        ('attendance', '0005_workshift_break_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlytimesheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlytimesheet',
            name='timesheet_type',
            field=models.CharField(choices=[('operations', 'Nhan vien van hanh'), ('teaching', 'Giao vien/Tro giang')], default='operations', max_length=20, verbose_name='Loai bang cong'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytimesheet',
            unique_together={('month', 'year', 'position', 'timesheet_type')},
        ),
    ]
