# Generated by Django 4.2.7 on 2026-08-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_basic_salary_and_more'),
        ('attendance', '0006_alter_monthlytimesheet_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceadjustment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Điều chỉnh công', 'verbose_name_plural': 'Điều chỉnh công'},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-start_date'], 'verbose_name': 'Bảng chấm công chi tiết cũ', 'verbose_name_plural': 'Bảng chấm công chi tiết cũ'},
        ),
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bảng chấm công tổng hợp cũ', 'verbose_name_plural': 'Bảng chấm công tổng hợp cũ'},
        ),
        migrations.AlterModelOptions(
            name='classsession',
            options={'ordering': ['-date', 'start_time'], 'verbose_name': 'Buổi học', 'verbose_name_plural': 'Buổi học'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'Lớp/Khóa học', 'verbose_name_plural': 'Lớp/Khóa học'},
        ),
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'verbose_name': 'Chấm công nhân viên vận hành', 'verbose_name_plural': 'Chấm công nhân viên vận hành'},
        ),
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'verbose_name': 'Chấm công nhân viên cũ', 'verbose_name_plural': 'Chấm công nhân viên cũ'},
        ),
        migrations.AlterModelOptions(
            name='employeeschedule',
            options={'ordering': ['-date', 'employee__code'], 'verbose_name': 'Lịch làm việc cũ', 'verbose_name_plural': 'Lịch làm việc cũ'},
        ),
        migrations.AlterModelOptions(
            name='monthlytimesheet',
            options={'ordering': ['-year', '-month', 'position__code'], 'verbose_name': 'Bảng công tháng', 'verbose_name_plural': 'Bảng công tháng'},
        ),
        migrations.AlterModelOptions(
            name='sessionattendance',
            options={'verbose_name': 'Chấm công buổi dạy', 'verbose_name_plural': 'Chấm công buổi dạy'},
        ),
        migrations.AlterModelOptions(
            name='staffschedule',
            options={'ordering': ['-date', 'employee__code'], 'verbose_name': 'Lịch ca nhân viên vận hành', 'verbose_name_plural': 'Lịch ca nhân viên vận hành'},
        ),
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'verbose_name': 'Phân công giảng dạy', 'verbose_name_plural': 'Phân công giảng dạy'},
        ),
        migrations.AlterModelOptions(
            name='timesheetapproval',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lịch sử duyệt bảng công', 'verbose_name_plural': 'Lịch sử duyệt bảng công'},
        ),
        migrations.AlterModelOptions(
            name='workshift',
            options={'verbose_name': 'Ca làm việc', 'verbose_name_plural': 'Ca làm việc'},
        ),
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('workday', 'Điều chỉnh ngày công'), ('hour', 'Điều chỉnh giờ dạy/làm'), ('paid_leave', 'Điều chỉnh nghỉ có lương'), ('unpaid_leave', 'Điều chỉnh nghỉ không lương'), ('note', 'Ghi chú')], max_length=20, verbose_name='Loại điều chỉnh'),
        ),
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='monthly_timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='attendance.monthlytimesheet', verbose_name='Bảng công tháng'),
        ),
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='reason',
            field=models.TextField(verbose_name='Lý do'),
        ),
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='apply_to_all_shifts',
            field=models.BooleanField(default=False, verbose_name='Chọn tất cả ca'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(choices=[('shift', 'Theo ca'), ('daily', 'Theo ngày')], max_length=20, verbose_name='Hình thức chấm công'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên bảng chấm công'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí áp dụng'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='work_shifts',
            field=models.ManyToManyField(blank=True, to='attendance.workshift', verbose_name='Ca làm việc'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='attendance_records',
            field=models.ManyToManyField(to='attendance.attendancerecord', verbose_name='Danh sách bảng chấm công chi tiết'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='month',
            field=models.IntegerField(default=1, verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên bảng chấm công tổng hợp'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí áp dụng'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='standard_workdays',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5, verbose_name='Số công chuẩn'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='transferred',
            field=models.BooleanField(default=False, verbose_name='Đã chuyển tính lương'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.course', verbose_name='Lớp/Khóa học'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='date',
            field=models.DateField(verbose_name='Ngày học'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(verbose_name='Giờ kết thúc'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phòng học'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(verbose_name='Giờ bắt đầu'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Đã xếp lịch'), ('completed', 'Đã dạy'), ('cancelled', 'Đã hủy'), ('makeup', 'Dạy bù')], default='scheduled', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Mã lớp/khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cấp độ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên lớp/khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='actual_work_days',
            field=models.FloatField(default=1, verbose_name='Số công đi làm thực tế'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='attendance.attendancerecord', verbose_name='Bảng chấm công cũ'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_status',
            field=models.CharField(choices=[('not_absent', 'Không nghỉ'), ('permitted_absence', 'Nghỉ có phép'), ('unpermitted_absence', 'Nghỉ không phép'), ('regime_absence', 'Nghỉ theo chế độ')], default='not_absent', max_length=20, verbose_name='Trạng thái nghỉ'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ vào'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ ra'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(verbose_name='Ngày chấm công'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='paid_work_days',
            field=models.FloatField(default=1, verbose_name='Số công hưởng lương'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='attendance.employeeschedule', verbose_name='Lịch làm việc cũ'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='staff_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='attendance.staffschedule', verbose_name='Lịch ca nhân viên'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift', verbose_name='Ca làm việc'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendance_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='attendance.attendancesummary', verbose_name='Bảng chấm công tổng hợp cũ'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='late_early_minutes',
            field=models.IntegerField(default=0, verbose_name='Đi muộn/về sớm (phút)'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='paid_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghỉ có lương'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='policy_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghỉ chế độ'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='unpaid_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghỉ không lương'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='workdays',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Số công làm việc'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='date',
            field=models.DateField(verbose_name='Ngày làm việc'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_schedules', to='employees.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='expected_work_days',
            field=models.FloatField(default=1, verbose_name='Số công dự kiến'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='work_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to='attendance.workshift', verbose_name='Ca làm việc'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='month',
            field=models.IntegerField(verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên bảng công tháng'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('approved', 'Đã duyệt'), ('locked', 'Đã khóa'), ('transferred', 'Đã chuyển lương')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='timesheet_type',
            field=models.CharField(choices=[('operations', 'Nhân viên vận hành'), ('teaching', 'Giáo viên/Trợ giảng')], default='operations', max_length=20, verbose_name='Loại bảng công'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='transferred',
            field=models.BooleanField(default=False, verbose_name='Đã chuyển tính lương'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='year',
            field=models.IntegerField(verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc thực tế'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu thực tế'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Đã duyệt'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.teacherassignment', verbose_name='Phân công'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='paid_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giờ tính lương'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='status',
            field=models.CharField(choices=[('taught', 'Đã dạy'), ('absent_excused', 'Nghỉ có phép'), ('absent_unexcused', 'Nghỉ không phép'), ('substituted', 'Có người dạy thay'), ('cancelled_by_center', 'Lớp hủy bởi trung tâm'), ('cancelled_by_teacher', 'Giáo viên hủy'), ('online', 'Dạy online'), ('makeup', 'Dạy bù')], default='taught', max_length=30, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateField(verbose_name='Ngày làm việc'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='employees.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='expected_work_days',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Công dự kiến'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='status',
            field=models.CharField(choices=[('planned', 'Đã xếp lịch'), ('cancelled', 'Đã hủy')], default='planned', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='work_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='attendance.workshift', verbose_name='Ca làm việc'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.classsession', verbose_name='Buổi học'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='employees.employee', verbose_name='Nhân sự'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='expected_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giờ dự kiến'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='pay_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Hệ số tính lương'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='role',
            field=models.CharField(choices=[('teacher', 'Giáo viên'), ('assistant', 'Trợ giảng'), ('substitute', 'Dạy thay')], default='teacher', max_length=20, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='timesheetapproval',
            name='action',
            field=models.CharField(choices=[('reviewed', 'Đã rà soát'), ('approved', 'Đã duyệt'), ('locked', 'Đã khóa'), ('reopened', 'Mở khóa')], max_length=20, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='timesheetapproval',
            name='monthly_timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='attendance.monthlytimesheet', verbose_name='Bảng công tháng'),
        ),
        migrations.AlterField(
            model_name='timesheetapproval',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='apply_to_all',
            field=models.BooleanField(default=False, verbose_name='Toàn đơn vị'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Số phút nghỉ giữa ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='check_in_end',
            field=models.TimeField(verbose_name='Chấm vào - Đến'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='check_in_start',
            field=models.TimeField(verbose_name='Chấm vào - Từ'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='check_out_end',
            field=models.TimeField(verbose_name='Chấm ra - Đến'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='check_out_start',
            field=models.TimeField(verbose_name='Chấm ra - Từ'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Mã ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='deduct_if_no_check_in',
            field=models.BooleanField(default=False, verbose_name='Trừ công nếu không có giờ vào'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='deduct_if_no_check_out',
            field=models.BooleanField(default=False, verbose_name='Trừ công nếu không có giờ ra'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employees.employee', verbose_name='Danh sách nhân viên'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.TimeField(verbose_name='Giờ kết thúc ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='has_break',
            field=models.BooleanField(default=False, verbose_name='Có nghỉ giữa ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='holiday_coefficient',
            field=models.FloatField(default=3, verbose_name='Hệ số ngày lễ'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên ca làm việc'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='normal_day_coefficient',
            field=models.FloatField(default=1, verbose_name='Hệ số ngày thường'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='rest_day_coefficient',
            field=models.FloatField(default=2, verbose_name='Hệ số ngày nghỉ'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.TimeField(verbose_name='Giờ bắt đầu ca'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='work_days',
            field=models.FloatField(default=1, verbose_name='Ngày công'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='work_hours',
            field=models.FloatField(default=0, verbose_name='Giờ công'),
        ),
    ]
