# Generated by Django 4.2.7 on 2026-07-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='File hop dong'),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Luong thang'), ('daily', 'Luong theo ngay cong'), ('shift', 'Luong theo ca'), ('hourly', 'Luong theo gio'), ('commission', 'Hoa hong/doanh so'), ('none', 'Khong ap dung luong co ban')], default='monthly', max_length=20, verbose_name='Loai luong'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Lương cơ bản'),
        ),
    ]
