# Generated by Django 4.2.7 on 2026-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_contract_file_contract_salary_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
        migrations.AlterField(
            model_name='contract',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mức lương / Đơn giá tính lương'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='File hợp đồng'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Lương tháng'), ('daily', 'Lương theo ngày công'), ('shift', 'Lương theo ca'), ('hourly', 'Lương theo giờ'), ('commission', 'Hoa hồng/doanh số'), ('none', 'Không áp dụng lương cơ bản')], default='monthly', max_length=20, verbose_name='Loại lương'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_form',
            field=models.CharField(blank=True, choices=[('fulltime', 'Toàn thời gian'), ('parttime', 'Bán thời gian'), ('shift', 'Theo ca'), ('contractor', 'Cộng tác viên'), ('remote', 'Từ xa'), ('hybrid', 'Kết hợp')], default='fulltime', max_length=20, null=True, verbose_name='Hình thức làm việc'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã phòng ban'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên phòng ban'),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã vị trí công việc'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên vị trí công việc'),
        ),
    ]
