# Generated by Django 4.2.7 on 2026-07-30 09:56

from django.db import migrations, models
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.IntegerField(default=payroll.models.current_month, verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('processing', 'Đang xử lý'), ('approved', 'Đã duyệt'), ('paid', 'Đã thanh toán'), ('disabled', 'Vô hiệu hóa')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(default=payroll.models.current_year, verbose_name='Năm'),
        ),
    ]
