# Generated by Django 4.2.7 on 2026-08-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendanceadjustment_options_and_more'),
        ('payroll', '0004_alter_payroll_month_alter_payroll_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='monthly_timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='attendance.monthlytimesheet', verbose_name='Bảng công tháng'),
        ),
    ]
